apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-24lo
  namespace: karthik-jk-tenant
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/stonesoupuicluster/uidev-user-workload@sha256:4f8e6945bf2e78271f54afc7461684c2d6d498825321bf80cb9dc06ff5e46e8e
        name: my-nodejs
        resources: {}
status: {}
